"""Add property filter fields

Revision ID: 08069cc08fc1
Revises: 6444f637fd98
Create Date: 2025-08-09 11:56:27.281062
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08069cc08fc1'
down_revision = '6444f637fd98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('supports_free_cancellation', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('supports_no_prepayment', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('neighbourhood', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'neighbourhood')
    op.drop_column('properties', 'supports_no_prepayment')
    op.drop_column('properties', 'supports_free_cancellation')
    # ### end Alembic commands ###


