"""add room_rates table

Revision ID: 64937c234878
Revises: 7badd
Create Date: 2025-08-09 22:49:29.352874
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64937c234878'
down_revision = '7badd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('includes_breakfast', sa.Boolean(), nullable=True),
    sa.Column('includes_parking', sa.Boolean(), nullable=True),
    sa.Column('free_cancellation', sa.Boolean(), nullable=True),
    sa.Column('refundable_until', sa.DateTime(), nullable=True),
    sa.Column('pay_at_property', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('check_in_date', sa.DATETIME(), nullable=False),
    sa.Column('check_out_date', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=24), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cart_id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('num_rooms', sa.INTEGER(), nullable=True),
    sa.Column('num_guests', sa.INTEGER(), nullable=True),
    sa.Column('base_price', sa.FLOAT(), nullable=True),
    sa.Column('genius_discount', sa.FLOAT(), nullable=True),
    sa.Column('taxes', sa.FLOAT(), nullable=True),
    sa.Column('total_price', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.drop_table('room_rates')
    # ### end Alembic commands ###


